/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sensordemo_JniUtils */

#ifndef _Included_com_sensordemo_JniUtils
#define _Included_com_sensordemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sensordemo_JniUtils
 * Method:    trainClassifierNative
 * Signature: (Ljava/lang/String;IIFILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sensordemo_JniUtils_trainClassifierNative
  (JNIEnv *, jobject, jstring, jint, jint, jfloat, jint, jstring);

/*
 * Class:     com_sensordemo_JniUtils
 * Method:    getMatrixNative
 * Signature: (I[F[F[F[F[F[F[F[F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sensordemo_JniUtils_getMatrixNative
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_sensordemo_JniUtils
 * Method:    doClassificationNative
 * Signature: ([[F[[IILjava/lang/String;[I[D)I
 */
JNIEXPORT jint JNICALL Java_com_sensordemo_JniUtils_doClassificationNative
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint, jstring, jintArray, jdoubleArray);

/*
 * Class:     com_sensordemo_JniUtils
 * Method:    testCallocNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sensordemo_JniUtils_testCallocNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
